resilience4j:
  circuitbreaker:
    instances:

      clinicAdminService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        record-exceptions:
          - java.lang.Exception
          - feign.FeignException
        ignore-exceptions:
          - java.lang.IllegalArgumentException

      physioDoctorService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        record-exceptions:
          - java.lang.Exception
          - feign.FeignException
        ignore-exceptions:
          - java.lang.IllegalArgumentException

      keycloak:
        register-health-indicator: true
        failure-rate-threshold: 50
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 4
        wait-duration-in-open-state: 1m

        record-exceptions:
          - java.lang.Exception
          - feign.FeignException
          - java.io.IOException
          - java.util.concurrent.TimeoutException

        ignore-exceptions:
          - java.lang.IllegalArgumentException
          - org.springframework.web.bind.MethodArgumentNotValidException
          - org.springframework.web.server.ResponseStatusException

  retry:
    instances:

      clinicAdminService:
        max-attempts: 3
        wait-duration: 2s

      bookingService:
        max-attempts: 3
        wait-duration: 2s

      physioDoctorService:
        max-attempts: 3
        wait-duration: 2s

      keycloak:
        max-attempts: 3
        wait-duration: 2s

  timelimiter:
    instances:

      bookingService:
        timeout-duration: 60s

      clinicAdminService:
        timeout-duration: 60s

      notificationService:
        timeout-duration: 60s

      physioDoctorService:
        timeout-duration: 60s

  ratelimiter:
    instances:

      keycloak:
        limit-for-period: 100
        limit-refresh-period: 1s
        timeout-duration: 2s