spring:
  application:
    name: notification-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/DermaCareNotifications?connectTimeoutMS=30000&socketTimeoutMS=60000

    redis:
      host: localhost
      port: 6379
      # password: your-password

  mvc:
    async:
      request-timeout: 60000

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 30000
            readTimeout: 60000

server:
  port: 9909

  servlet:
    context-path: /api

  tomcat:
    connection-timeout: 60s

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

  client:
    register-with-eureka: true
    fetch-registry: true

    healthcheck:
      enabled: true

    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  server:
    base-path: /

  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

info:
  app:
    name: notification-service
    description: Service responsible for handling notifications related to bookings
    version: 1.0.0

app:
  firebase-configuration-file: firebase-key.json

logging:
  level:
    org.springframework.web: INFO
    com.dermacare.notification_service: DEBUG

resilience4j:
  circuitbreaker:
    instances:

      clinicAdminService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        record-exceptions:
          - java.lang.Exception
          - feign.FeignException
        ignore-exceptions:
          - java.lang.IllegalArgumentException

      physioDoctorService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        record-exceptions:
          - java.lang.Exception
          - feign.FeignException
        ignore-exceptions:
          - java.lang.IllegalArgumentException

  retry:
    instances:

      clinicAdminService:
        max-attempts: 3
        wait-duration: 2s

      bookingService:
        max-attempts: 3
        wait-duration: 2s

      physioDoctorService:
        max-attempts: 3
        wait-duration: 2s

  timelimiter:
    instances:

      bookingService:
        timeout-duration: 60s

      clinicAdminService:
        timeout-duration: 60s

      notificationService:
        timeout-duration: 60s

      physioDoctorService:
        timeout-duration: 60s