spring:
  application:
    name: bookingservice

#  config:
#    import: optional:application-secrets.yml

  data:
    mongodb:
      uri: mongodb://localhost:27017/customerAppointments?connectTimeoutMS=30000&socketTimeoutMS=60000

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 30000
            readTimeout: 60000

  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: 9900

  servlet:
    context-path: /api

  shutdown: graceful

  compression:
    enabled: true
    mime-types:
      - application/json
      - text/html
      - text/plain

# =========================================================
# WHATSAPP
# =========================================================

#whatsapp:
#  base-url: 
#  auth-key: 
#  phone-number-id:  123456789012345
#  booking-confirmation-template-id:  booking_confirmation 


# =========================================================
# AWS S3
# =========================================================

#aws:
#  accessKeyId: 
#  secretAccessKey: 
#  region: ap-south-1
#  s3:
#    bucket: physiocare-prod-storage

# =========================================================
# EUREKA
# =========================================================

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true

# =========================================================
# RESILIENCE4J
# =========================================================

resilience4j:
  circuitbreaker:
    instances:
      bookingService:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50

  retry:
   instances:
    paymentService:
    max-attempts: 3
    wait-duration: 2s

  timelimiter:
    instances:
      bookingService:
        timeout-duration: 60s

  ratelimiter:
    instances:
     bookingApi:
      limit-for-period: 50
      limit-refresh-period: 1m
      timeout-duration: 1s

# =========================================================
# ACTUATOR
# =========================================================

management:
  server:
    base-path: /

  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

# =========================================================
# INFO
# =========================================================

info:
  app:
    name: bookingservice
    description: Service responsible for booking appointments
    version: 1.0.0

# =========================================================
# LOGGING
# =========================================================

logging:
  level:
    root: INFO