spring:
  application:
    name: bookingservice

#  config:
#    import: optional:application-secrets.yml


  data:
    mongodb:
      uri: mongodb://localhost:27017/customerAppointments?connectTimeoutMS=30000&socketTimeoutMS=60000
      
    redis:
      host: localhost
      port: 6379
#      password: your-password


  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 30000
            readTimeout: 60000


  lifecycle:
    timeout-per-shutdown-phase: 30s

server:

  port: 9900

  servlet:
    context-path: /api

  shutdown: graceful

  compression:
    enabled: true
    mime-types:
      - application/json
      - text/html
      - text/plain

spring.lifecycle:
  timeout-per-shutdown-phase: 30s

# =========================================================
# WHATSAPP
# =========================================================
whatsapp:
  base-url: 
  auth-key: 
  phone-number-id: 
  booking-confirmation-template-id: 

# =========================================================
# AWS S3
# =========================================================

aws:
  accessKeyId: 
  secretAccessKey: 
  region: ap-south-1
  s3:
    bucket: physiocare-prod-storage

# =========================================================
# EUREKA
# =========================================================

eureka:

  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true

# =========================================================
# RESILIENCE4J
# =========================================================

resilience4j:
  circuitbreaker:
    instances:

      adminService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        record-exceptions:
          - java.lang.Exception
          - feign.FeignException
        ignore-exceptions:
          - java.lang.IllegalArgumentException

      clinicAdminService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        record-exceptions:
          - java.lang.Exception
          - feign.FeignException
        ignore-exceptions:
          - java.lang.IllegalArgumentException

      notificationService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        record-exceptions:
          - java.lang.Exception
          - feign.FeignException
        ignore-exceptions:
          - java.lang.IllegalArgumentException

      physioDoctorService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        record-exceptions:
          - java.lang.Exception
          - feign.FeignException
        ignore-exceptions:

      keyclaok:
       failure-rate-threshold: 50
       sliding-window-size: 10
       sliding-window-type: COUNT_BASED
       minimum-number-of-calls: 5
       automatic-transition-from-open-to-half-open-enabled: true
       permitted-number-of-calls-in-half-open-state: 4
       wait-duration-in-open-state: 1m
       record-exceptions:
         - java.lang.Exception
         - feign.FeignException
         - java.io.IOException
         - java.util.concurrent.TimeoutException
       ignore-exceptions:
         - java.lang.IllegalArgumentException
         - org.springframework.web.bind.MethodArgumentNotValidException
         - org.springframework.web.server.ResponseStatusException

  retry:
    instances:

      adminService:
        max-attempts: 3
        wait-duration: 2s

      clinicAdminService:
        max-attempts: 3
        wait-duration: 2s

      notificationService:
        max-attempts: 3
        wait-duration: 2s

      physioDoctorService:
        max-attempts: 3
        wait-duration: 2s

      keyclaok:
        max-attempts: 3
        wait-duration: 2s

  timelimiter:
    instances:

      bookingService:
        timeout-duration: 60s

      clinicAdminService:
        timeout-duration: 60s

      notificationService:
        timeout-duration: 60s

      physioDoctorService:
        timeout-duration: 60s

# =========================================================
# RATE LIMIT CONFIG
# =========================================================
  ratelimiter:
    instances:
     bookingService:
      limit-for-period: 50
      limit-refresh-period: 1m
      timeout-duration: 1s
     keyclaok:
      limit-for-period: 100
      limit-refresh-period: 1s
      timeout-duration: 2s

# =========================================================
# ACTUATOR
# =========================================================

management:
  server:
    base-path: /
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

# =========================================================
# INFO
# =========================================================

info:

  app:
    name: bookingservice
    description: Service responsible for booking appointments
    version: 1.0.0

# =========================================================
# LOGGING
# =========================================================

logging:
  level:
    root: INFO
