# ===============================
# Application
# ===============================
spring.application.name=physiotherapydoctor-service

# ===============================
# Server Configuration
# ===============================
server.port=8888
server.servlet.context-path=/api

# ===============================
# Eureka Configuration
# ===============================
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.healthcheck.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90

# ===============================
# MongoDB Configuration
# ===============================
spring.data.mongodb.uri=mongodb://localhost:27017/physiotherapydoctorservice?connectTimeoutMS=30000&socketTimeoutMS=60000&serverSelectionTimeoutMS=30000

# ===============================
# OpenFeign Timeouts
# ===============================
spring.cloud.openfeign.client.config.default.connectTimeout=30000
spring.cloud.openfeign.client.config.default.readTimeout=60000

# ===============================
# Actuator Configuration
# ===============================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.server.base-path=/

## ===============================
## AWS S3
## ===============================

#aws.region=ap-south-1
#aws.s3.bucket=physiocare-prod-storage

# ===============================
# Logging Configuration
# ===============================
logging.level.org.springframework.web=INFO
logging.level.physiotherapydoctor=DEBUG


jwt.secret-key= 5z6tUDDVjw1B+Cx5v9M98KUU8+WInRNa2NxgAL9ys58=
refresh-token.secret-key= /tI94qx2IMdBVvAzfPhwJoN/Dy0YL4c7w/vwOxesMt0=

# ===============================
# Resilience4j
# ===============================
resilience4j.circuitbreaker.instances.physiotherapydoctorService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.physiotherapydoctorService.sliding-window-size=10
resilience4j.circuitbreaker.instances.physiotherapydoctorService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.physiotherapydoctorService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.physiotherapydoctorService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.physiotherapydoctorService.permitted-number-of-calls-in-half-open-state=4
resilience4j.circuitbreaker.instances.physiotherapydoctorService.wait-duration-in-open-state=1m

# Record these exceptions as failures
resilience4j.circuitbreaker.instances.physiotherapydoctorService.record-exceptions[0]=java.lang.Exception
resilience4j.circuitbreaker.instances.physiotherapydoctorService.record-exceptions[1]=feign.FeignException
resilience4j.circuitbreaker.instances.physiotherapydoctorService.record-exceptions[2]=java.io.IOException
resilience4j.circuitbreaker.instances.physiotherapydoctorService.record-exceptions[3]=java.util.concurrent.TimeoutException

# Ignore these exceptions
resilience4j.circuitbreaker.instances.physiotherapydoctorService.ignore-exceptions[0]=java.lang.IllegalArgumentException
resilience4j.circuitbreaker.instances.physiotherapydoctorService.ignore-exceptions[1]=org.springframework.web.bind.MethodArgumentNotValidException
resilience4j.circuitbreaker.instances.physiotherapydoctorService.ignore-exceptions[2]=org.springframework.web.server.ResponseStatusException

resilience4j.retry.instances.physiotherapydoctorService.max-attempts=3
resilience4j.retry.instances.physiotherapydoctorService.wait-duration=2s

resilience4j.ratelimiter.instances.physiotherapydoctorService.limit-for-period=20
resilience4j.ratelimiter.instances.physiotherapydoctorService.limit-refresh-period=1s
resilience4j.ratelimiter.instances.physiotherapydoctorService.timeout-duration=2s


#spring.config.import=optional:classpath:application-secrets.properties

#================Circuit breaker==========================================


# ===============================
# Booking Service
# ===============================

resilience4j.circuitbreaker.instances.bookingService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.bookingService.sliding-window-size=10
resilience4j.circuitbreaker.instances.bookingService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.bookingService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.bookingService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.bookingService.permitted-number-of-calls-in-half-open-state=4
resilience4j.circuitbreaker.instances.bookingService.wait-duration-in-open-state=1m

resilience4j.retry.instances.bookingService.max-attempts=3
resilience4j.retry.instances.bookingService.wait-duration=2s

resilience4j.ratelimiter.instances.bookingService.limit-for-period=20
resilience4j.ratelimiter.instances.bookingService.limit-refresh-period=1s
resilience4j.ratelimiter.instances.bookingService.timeout-duration=2s

# ===============================
# Clinic Admin Service
# ===============================

resilience4j.circuitbreaker.instances.clinicAdminService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.clinicAdminService.sliding-window-size=10
resilience4j.circuitbreaker.instances.clinicAdminService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.clinicAdminService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.clinicAdminService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.clinicAdminService.permitted-number-of-calls-in-half-open-state=4
resilience4j.circuitbreaker.instances.clinicAdminService.wait-duration-in-open-state=1m

resilience4j.retry.instances.clinicAdminService.max-attempts=3
resilience4j.retry.instances.clinicAdminService.wait-duration=2s

resilience4j.ratelimiter.instances.clinicAdminService.limit-for-period=20
resilience4j.ratelimiter.instances.clinicAdminService.limit-refresh-period=1s
resilience4j.ratelimiter.instances.clinicAdminService.timeout-duration=2s

# ===============================
# Admin Service
# ===============================

resilience4j.circuitbreaker.instances.adminService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.adminService.sliding-window-size=10
resilience4j.circuitbreaker.instances.adminService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.adminService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.adminService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.adminService.permitted-number-of-calls-in-half-open-state=4
resilience4j.circuitbreaker.instances.adminService.wait-duration-in-open-state=1m

resilience4j.retry.instances.adminService.max-attempts=3
resilience4j.retry.instances.adminService.wait-duration=2s

resilience4j.ratelimiter.instances.adminService.limit-for-period=20
resilience4j.ratelimiter.instances.adminService.limit-refresh-period=1s
resilience4j.ratelimiter.instances.adminService.timeout-duration=2s

# ===============================
# Notification Service
# ===============================

resilience4j.circuitbreaker.instances.notificationService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.notificationService.sliding-window-size=10
resilience4j.circuitbreaker.instances.notificationService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.notificationService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.notificationService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.notificationService.permitted-number-of-calls-in-half-open-state=4
resilience4j.circuitbreaker.instances.notificationService.wait-duration-in-open-state=1m

resilience4j.retry.instances.notificationService.max-attempts=3
resilience4j.retry.instances.notificationService.wait-duration=2s

resilience4j.ratelimiter.instances.notificationService.limit-for-period=20
resilience4j.ratelimiter.instances.notificationService.limit-refresh-period=1s
resilience4j.ratelimiter.instances.notificationService.timeout-duration=2s

# ===============================
# Keycloak Service
# ===============================

resilience4j.circuitbreaker.instances.keycloakService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.keycloakService.sliding-window-size=10
resilience4j.circuitbreaker.instances.keycloakService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.keycloakService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.keycloakService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.keycloakService.permitted-number-of-calls-in-half-open-state=4
resilience4j.circuitbreaker.instances.keycloakService.wait-duration-in-open-state=1m

resilience4j.retry.instances.keycloakService.max-attempts=3
resilience4j.retry.instances.keycloakService.wait-duration=2s

resilience4j.ratelimiter.instances.keycloakService.limit-for-period=20
resilience4j.ratelimiter.instances.keycloakService.limit-refresh-period=1s
resilience4j.ratelimiter.instances.keycloakService.timeout-duration=2s

