# ===============================
# Application
# ===============================
spring.application.name=clinicadmin
server.port=8080

# ===============================
# Eureka
# ===============================
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.healthcheck.enabled=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90

# ===============================
# MongoDB
# ===============================
spring.data.mongodb.uri=mongodb://localhost:27017/clinicadminservice?connectTimeoutMS=30000&socketTimeoutMS=60000

# ===============================
# Server Timeouts
# ===============================
server.tomcat.connection-timeout=60s
spring.mvc.async.request-timeout=60000

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.mail.enabled=false

# ===============================
# Mail Configuration
# ===============================
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:dermacare382@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:ejavgihpzhyfsiaz}

spring.mail.protocol=smtp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.debug=false

# ===============================
# Resilience4j
# ===============================
resilience4j.circuitbreaker.instances.adminService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.adminService.sliding-window-size=10
resilience4j.circuitbreaker.instances.adminService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.adminService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.adminService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.adminService.permitted-number-of-calls-in-half-open-state=4
resilience4j.circuitbreaker.instances.adminService.wait-duration-in-open-state=1m

# Record these exceptions as failures
resilience4j.circuitbreaker.instances.adminService.record-exceptions[0]=java.lang.Exception
resilience4j.circuitbreaker.instances.adminService.record-exceptions[1]=feign.FeignException
resilience4j.circuitbreaker.instances.adminService.record-exceptions[2]=java.io.IOException
resilience4j.circuitbreaker.instances.adminService.record-exceptions[3]=java.util.concurrent.TimeoutException

# Ignore these exceptions
resilience4j.circuitbreaker.instances.adminService.ignore-exceptions[0]=java.lang.IllegalArgumentException
resilience4j.circuitbreaker.instances.adminService.ignore-exceptions[1]=org.springframework.web.bind.MethodArgumentNotValidException
resilience4j.circuitbreaker.instances.adminService.ignore-exceptions[2]=org.springframework.web.server.ResponseStatusException

resilience4j.retry.instances.adminService.max-attempts=3
resilience4j.retry.instances.adminService.wait-duration=2s


resilience4j.circuitbreaker.instances.bookingService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.bookingService.sliding-window-size=10
resilience4j.circuitbreaker.instances.bookingService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.bookingService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.bookingService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.bookingService.permitted-number-of-calls-in-half-open-state=4
resilience4j.circuitbreaker.instances.bookingService.wait-duration-in-open-state=1m

# Record these exceptions as failures
resilience4j.circuitbreaker.instances.bookingService.record-exceptions[0]=java.lang.Exception
resilience4j.circuitbreaker.instances.bookingService.record-exceptions[1]=feign.FeignException
resilience4j.circuitbreaker.instances.bookingService.record-exceptions[2]=java.io.IOException
resilience4j.circuitbreaker.instances.bookingService.record-exceptions[3]=java.util.concurrent.TimeoutException

# Ignore these exceptions
resilience4j.circuitbreaker.instances.bookingService.ignore-exceptions[0]=java.lang.IllegalArgumentException
resilience4j.circuitbreaker.instances.bookingService.ignore-exceptions[1]=org.springframework.web.bind.MethodArgumentNotValidException
resilience4j.circuitbreaker.instances.bookingService.ignore-exceptions[2]=org.springframework.web.server.ResponseStatusException

resilience4j.retry.instances.bookingService.max-attempts=3
resilience4j.retry.instances.bookingService.wait-duration=2s


resilience4j.circuitbreaker.instances.customerService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.customerService.sliding-window-size=10
resilience4j.circuitbreaker.instances.customerService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.customerService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.customerService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.customerService.permitted-number-of-calls-in-half-open-state=4
resilience4j.circuitbreaker.instances.customerService.wait-duration-in-open-state=1m

# Record these exceptions as failures
resilience4j.circuitbreaker.instances.customerService.record-exceptions[0]=java.lang.Exception
resilience4j.circuitbreaker.instances.customerService.record-exceptions[1]=feign.FeignException
resilience4j.circuitbreaker.instances.customerService.record-exceptions[2]=java.io.IOException
resilience4j.circuitbreaker.instances.customerService.record-exceptions[3]=java.util.concurrent.TimeoutException

# Ignore these exceptions
resilience4j.circuitbreaker.instances.customerService.ignore-exceptions[0]=java.lang.IllegalArgumentException
resilience4j.circuitbreaker.instances.customerService.ignore-exceptions[1]=org.springframework.web.bind.MethodArgumentNotValidException
resilience4j.circuitbreaker.instances.customerService.ignore-exceptions[2]=org.springframework.web.server.ResponseStatusException

resilience4j.retry.instances.customerService.max-attempts=3
resilience4j.retry.instances.customerService.wait-duration=2s


resilience4j.circuitbreaker.instances.notificationService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.notificationService.sliding-window-size=10
resilience4j.circuitbreaker.instances.notificationService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.notificationService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.notificationService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.notificationService.permitted-number-of-calls-in-half-open-state=4
resilience4j.circuitbreaker.instances.notificationService.wait-duration-in-open-state=1m

# Record these exceptions as failures
resilience4j.circuitbreaker.instances.notificationService.record-exceptions[0]=java.lang.Exception
resilience4j.circuitbreaker.instances.notificationService.record-exceptions[1]=feign.FeignException
resilience4j.circuitbreaker.instances.notificationService.record-exceptions[2]=java.io.IOException
resilience4j.circuitbreaker.instances.notificationService.record-exceptions[3]=java.util.concurrent.TimeoutException

# Ignore these exceptions
resilience4j.circuitbreaker.instances.notificationService.ignore-exceptions[0]=java.lang.IllegalArgumentException
resilience4j.circuitbreaker.instances.notificationService.ignore-exceptions[1]=org.springframework.web.bind.MethodArgumentNotValidException
resilience4j.circuitbreaker.instances.notificationService.ignore-exceptions[2]=org.springframework.web.server.ResponseStatusException

resilience4j.retry.instances.notificationService.max-attempts=3
resilience4j.retry.instances.notificationService.wait-duration=2s


resilience4j.circuitbreaker.instances.physioDoctorService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.physioDoctorService.sliding-window-size=10
resilience4j.circuitbreaker.instances.physioDoctorService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.physioDoctorService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.physioDoctorService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.physioDoctorService.permitted-number-of-calls-in-half-open-state=4
resilience4j.circuitbreaker.instances.physioDoctorService.wait-duration-in-open-state=1m

# Record these exceptions as failures
resilience4j.circuitbreaker.instances.physioDoctorService.record-exceptions[0]=java.lang.Exception
resilience4j.circuitbreaker.instances.physioDoctorService.record-exceptions[1]=feign.FeignException
resilience4j.circuitbreaker.instances.physioDoctorService.record-exceptions[2]=java.io.IOException
resilience4j.circuitbreaker.instances.physioDoctorService.record-exceptions[3]=java.util.concurrent.TimeoutException

# Ignore these exceptions
resilience4j.circuitbreaker.instances.physioDoctorService.ignore-exceptions[0]=java.lang.IllegalArgumentException
resilience4j.circuitbreaker.instances.physioDoctorService.ignore-exceptions[1]=org.springframework.web.bind.MethodArgumentNotValidException
resilience4j.circuitbreaker.instances.physioDoctorService.ignore-exceptions[2]=org.springframework.web.server.ResponseStatusException

resilience4j.retry.instances.physioDoctorService.max-attempts=3
resilience4j.retry.instances.physioDoctorService.wait-duration=2s


resilience4j.circuitbreaker.instances.keyclaok.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.keyclaok.sliding-window-size=10
resilience4j.circuitbreaker.instances.keyclaok.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.keyclaok.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.keyclaok.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.keyclaok.permitted-number-of-calls-in-half-open-state=4
resilience4j.circuitbreaker.instances.keyclaok.wait-duration-in-open-state=1m

# Record these exceptions as failures
resilience4j.circuitbreaker.instances.keyclaok.record-exceptions[0]=java.lang.Exception
resilience4j.circuitbreaker.instances.keyclaok.record-exceptions[1]=feign.FeignException
resilience4j.circuitbreaker.instances.keyclaok.record-exceptions[2]=java.io.IOException
resilience4j.circuitbreaker.instances.keyclaok.record-exceptions[3]=java.util.concurrent.TimeoutException

# Ignore these exceptions
resilience4j.circuitbreaker.instances.keyclaok.ignore-exceptions[0]=java.lang.IllegalArgumentException
resilience4j.circuitbreaker.instances.keyclaok.ignore-exceptions[1]=org.springframework.web.bind.MethodArgumentNotValidException
resilience4j.circuitbreaker.instances.keyclaok.ignore-exceptions[2]=org.springframework.web.server.ResponseStatusException

resilience4j.retry.instances.keyclaok.max-attempts=3
resilience4j.retry.instances.keyclaok.wait-duration=2s

resilience4j.ratelimiter.instances.keyclaok.limit-for-period=20
resilience4j.ratelimiter.instances.keyclaok.limit-refresh-period=1s
resilience4j.ratelimiter.instances.keyclaok.timeout-duration=2s

# ===============================
# RATE LIMITING
# ===============================
resilience4j.ratelimiter.instances.clinicAdminService.limit-for-period=20
resilience4j.ratelimiter.instances.clinicAdminService.limit-refresh-period=1s
resilience4j.ratelimiter.instances.clinicAdminService.timeout-duration=2s

# ===============================
# AWS S3
# ===============================
# aws.access-key= 
# aws.secret-key=
# aws.region=ap-south-1
# aws.s3.bucket=physiocare-prod-storage

# ===============================

# Firebase

# ===============================

app.firebase-configuration-file=firebase-key.json

aws.access-key=      
aws.secret-key=
aws.region=ap-south-1
aws.s3.bucket=physiocare-prod-storage

# ===============================

# WhatsApp
# ===============================

# whatsapp.base-url=
# whatsapp.auth-key= 
# whatsapp.phone-number-id=123456789012345
# whatsapp.single-user-notification-template-id=payment_confirmation

# ===============================
# Logging
# ===============================
logging.level.org.springframework.web=INFO
logging.level.com.clinicadmin=DEBUG

# ===============================
# OpenFeign Timeouts
# ===============================
spring.cloud.openfeign.client.config.default.connectTimeout=30000

spring.cloud.openfeign.client.config.default.readTimeout=60000

jwt.secret-key= at2RnSxjbjRpes3loPD6uchWRigFuBiESU69Orej0KI=

refresh-token.secret-key= qEfuNDQ5Tu3YRV8YZmrCg369OpjVvmafG0fz54g9QUA=

# =========================================================
# CACHE
# =========================================================
spring.data.redis.host=localhost
spring.data.redis.port=6379
#spring.data.redis.password=

#spring.config.import=optional:classpath:application-secrets.properties

#spring.application.name=clinicadmin
#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true
#server.port=8080
#eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
#spring.data.mongodb.uri=mongodb://mongodb:27017/clinicadminservice
#
##--------------------------Actuator--------------------------------
#management.endpoints.web.exposure.include=health,info,metrics,env,beans,loggers


